### ISSUE TITLE
IntelMausi kext missing, despite it being defined

### ISSUE THREAD

**Issue by stephendt** [blacklizard/Hackintosh-Opencore-Guide-HP8300-SFF-i5-3470-Catalina#1]
Hi there,

It appears that there is an issue with the config.plist, since it is not finding the IntelMausi.kext, even though it is in the kexts folder on my boot partition.

Please advise. Thank you.

**Comment by stephendt** [comment]
The problem is that it's IntelMausiEthernet, not IntelMausi.

https://github.com/Mieze/IntelMausiEthernet

I renamed it and it seems OK now.

**Comment by blacklizard** [comment]
> The problem is that it's IntelMausiEthernet, not IntelMausi.
> 
> https://github.com/Mieze/IntelMausiEthernet
> 
> I renamed it and it seems OK now.

use this instead https://github.com/acidanthera/IntelMausi
